name: Pull Request Workflow

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  check-build-test:
    name: Check, Build & Test
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.head_commit.message, '#nobuild') }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set Up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Coursier Caching
        uses: coursier/cache-action@v6

      - name: Run scalafmt via sbt
        run: sbt scalafmtSbtCheck scalafmtCheck test:scalafmtCheck

      - name: Build & Test All Projects
        run: |
          sbt -v clean test

      - name: Cleanup Before Caching
        shell: bash
        run: |
          rm -rf "$HOME/.ivy2/local" || true
          find $HOME/Library/Caches/Coursier/v1 -name "ivydata-*.properties" -delete || true
          find $HOME/.ivy2/cache                -name "ivydata-*.properties" -delete || true
          find $HOME/.cache/coursier/v1         -name "ivydata-*.properties" -delete || true
          find $HOME/.sbt                       -name "*.lock"               -delete || true
